### ISSUE TITLE
Data links are not available.

### ISSUE THREAD

**Issue by n4ndoz** [deepmind/deepmind-research#39] opened 2020-03-09 20:37 UTC
Trying to download from the provided links on Readme.md is not working. Link is down or expired. Please, provide a valid link for the data.

**Comment by Augustin-Zidek** [comment] 2020-03-10 13:07
Could you clarify which README.md you mean?

**Comment by n4ndoz** [comment] 2020-03-10 18:33
Hi, sorry for not specifying. The README I refer to is the one at AlphaFold CASP13 's repository. Link below:

https://github.com/deepmind/deepmind-research/blob/master/alphafold_casp13/README.md

There are links there to bit.ly but they look expired.

**Comment by Augustin-Zidek** [comment] 2020-03-10 20:14
I tried all of the links and they work fine for me.

However, we host the data on Google Cloud Storage (https://storage.googleapis.com/) and that domain seems to be blocked in China (and maybe some other countries too?). So that might be the reason. 

You can test your access using this direct link to the license file: https://storage.googleapis.com/alphafold_casp13_data/LICENSE.txt.

**Comment by diegolascasas** [comment] 2020-04-07 12:24
Hi @n4ndoz,
Were you able access the links?
Closing this for now since we could not reproduce it, but feel free to reopen.

**Closed by diegolascasas** 2020-04-07 12:24 UTC

**Comment by n4ndoz** [comment] 2020-04-12 04:28
Hi! Sorry for the delay, suffered an accident. 
I have access now to the data. THank you.
The only issue is that I cannot resolve storage.googleapis.com on curl. But already download at home and "SCPing" files to lab. Thank you a lot.
